<?php

namespace app\modules\admin\models;

use Yii;

/**
 * This is the model class for table "courses".
 *
 * @property integer $id
 * @property string $title
 * @property string $anons
 * @property string $text
 * @property string $keywords
 * @property string $description
 * @property string $leftcol
 * @property string $price
 * @property integer $parent_id
 * @property string $backgroundimg
 * @property string $img
 * @property integer $show_detail
 * @property string $symbol
 * @property string $title_ru
 * @property string $title_en
 * @property string $anons_ru
 * @property string $anons_en
 * @property string $text_ru
 * @property string $text_en
 * @property string $keywords_ru
 * @property string $keywords_en
 * @property string $description_ru
 * @property string $description_en
 * @property string $leftcol_ru
 * @property string $leftcol_en
 */
class Courses extends AppTableModel
{
    public $bg;

    public $image;
    public $imageAlt;
    public $imageTitle;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'courses';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['image'], 'file', 'extensions' => 'png, jpg'],
            [['imageAlt','imageTitle'], 'string'],
            [['bg'], 'file', 'extensions' => 'png, jpg'],
            [['title','sort'], 'required'],
            [['anons', 'text', 'anons_ru', 'anons_en', 'text_ru', 'text_en', 'leftcol', 'leftcol_ru', 'leftcol_en'], 'string'],
            [['parent_id', 'show_detail', 'sort'], 'integer'],
            [['title'], 'string', 'max' => 254],
            [['subtitle_ru','subtitle_en','subtitle','keywords', 'description', 'backgroundimg', 'symbol', 'title_ru', 'title_en', 'keywords_ru', 'keywords_en', 'description_ru', 'description_en'], 'string', 'max' => 255],
            [['price'], 'string', 'max' => 10],
            [['table'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'subtitle' => 'Подзаголовок',
            'anons' => 'Анонс',
            'text' => 'Текст',
            'keywords' => 'Keywords',
            'description' => 'Description',
            'leftcol' => 'Левая колонка',
            'price' => 'Цена',
            'parent_id' => 'Родительский курс',
            'bg' => 'Фоновая картинка',
            'image' => 'Картинка',
            'imageAlt' => 'Картинка Alt',
            'imageTitle' => 'Картинка Title',
            'show_detail' => 'Показывать детальную страницу',
            'symbol' => 'Символьный код',
            'title_ru' => 'Заголовок Ru',
            'subtitle_ru' => 'Подзаголовок Ru',
            'title_en' => 'Заголовок En',
            'subtitle_en' => 'Подзаголовок En',
            'anons_ru' => 'Анонс Ru',
            'anons_en' => 'Анонс En',
            'text_ru' => 'Текст Ru',
            'text_en' => 'Текст En',
            'keywords_ru' => 'Keywords Ru',
            'keywords_en' => 'Keywords En',
            'description_ru' => 'Description Ru',
            'description_en' => 'Description En',
            'leftcol_ru' => 'Левая колонка Ru',
            'leftcol_en' => 'Левая колонка En',
            'sort' => 'Сортировка',
            'table' => 'Таблица(ы) (Для выбора нескольких таблиц - кнопка Ctrl+левая кнопка мыши)',
        ];
    }
    public function getCourses(){
        return $this->hasOne(Courses::className(), ['id'=>'parent_id']);
    }

    public function beforeSave($insert)
    {
        if($this->bg){
            $this->backgroundimg = $this->bg->baseName . '.' . $this->bg->extension;
        }

        if($this->image){
            $imgName = $this->image->baseName . '.' . $this->image->extension;
            $arr = [
                'img' => $imgName,
                'alt' => $this->imageAlt,
                'title' => $this->imageTitle,
            ];
            $this->img = json_encode($arr);
        }else{
            $arr = [
                'img' => $this->img,
                'alt' => $this->imageAlt,
                'title' => $this->imageTitle,
            ];
            $this->img = json_encode($arr);
        }
        //print_r($this->img);
        return parent::beforeSave($insert);
    }

    public function afterFind()
    {
        $arr = json_decode($this->img);
        $this->img = $arr->img;
        $this->imageAlt = $arr->alt;
        $this->imageTitle = $arr->title;

        parent::afterFind(); // TODO: Change the autogenerated stub
    }
    

    public function upload()
    {
        if ($this->validate()) {
            $this->bg->saveAs(Yii::getAlias("@webroot").'/images/' . $this->bg->baseName . '.' . $this->bg->extension);
            return true;
        } else {
            return false;
        }
    }

    public function upload1()
    {
        if ($this->validate()) {
            $this->image->saveAs(Yii::getAlias("@webroot").'/images/' . $this->image->baseName . '.' . $this->image->extension);
            return true;
        } else {
            return false;
        }
    }
    
}
