<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 19.10.2016
 * Time: 16:55
 */

namespace app\modules\admin\models;


use Yii;

class Imgmodel extends \yii\db\ActiveRecord
{
    public $image;
    public $imageAlt;
    public $imageTitle;

    protected $rule = [['image'], 'file', 'extensions' => 'png, jpg'];
    protected $rule2 = [['imageAlt','imageTitle'], 'string'];


    public function beforeSave($insert)
    {
        if($this->image){
            $imgName = $this->image->baseName . '.' . $this->image->extension;
            $arr = [
                'img' => $imgName,
                'alt' => $this->imageAlt,
                'title' => $this->imageTitle,
            ];
            $this->img = json_encode($arr);
        }else{
            $arr = [
                'img' => $this->img,
                'alt' => $this->imageAlt,
                'title' => $this->imageTitle,
            ];
            $this->img = json_encode($arr);
        }
        //print_r($this->img);
        return parent::beforeSave($insert);
    }

    public function afterFind()
    {
        $arr = json_decode($this->img);
        $this->img = $arr->img;
        $this->imageAlt = $arr->alt;
        $this->imageTitle = $arr->title;

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function upload()
    {
        if ($this->validate()) {
            $this->image->saveAs(Yii::getAlias("@webroot").'/images/' . $this->image->baseName . '.' . $this->image->extension);
            return true;
        } else {
            return false;
        }
    }
}