<?php

namespace app\modules\admin\models;

use Yii;

/**
 * This is the model class for table "levels".
 *
 * @property integer $id
 * @property string $left_column
 * @property string $left_column_ru
 * @property string $left_column_en
 * @property string $text
 * @property string $text_ru
 * @property string $text_en
 * @property string $page
 */
class Levels extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'levels';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['page'], 'safe'],
            [['page','title'], 'required'],
            [['text', 'text_ru', 'text_en','left_column_plus','left_column_plus_ru','left_column_plus_en'], 'string'],
            [['left_column', 'left_column_ru', 'left_column_en', 'price'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'title_ru' => 'Название Ru',
            'title_en' => 'Название En',
            'left_column' => 'Средняя колонка',
            'left_column_ru' => 'Средняя колонка Ru',
            'left_column_en' => 'Средняя колонка En',
            'text' => 'Текст',
            'text_ru' => 'Текст Ru',
            'text_en' => 'Текст En',
            'page' => 'Страница',
            'price' => 'Цена',
            'period' => 'Период',
            'period_ru' => 'Период',
            'period_en' => 'Период',
            'left_column_plus' => 'Нижняя колонка ',
            'left_column_plus_ru' => 'Нижняя колонка Ru ',
            'left_column_plus_en' => 'Нижняя колонка En ',
        ];
    }

    public function afterFind()
    {
        if(strlen($this->page)>1){
            $arr = explode("|", $this->page);
            unset($arr[0]);
            unset($arr[count($arr)]);
            $this->page = $arr;
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->page = "|" . implode("|", $this->page) . "|" ;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getPages(){
        $coures = Courses::find()->where("id IN(4,50,51)")->all();
        foreach ($coures as $item) {
            $item->id = "c".$item->id ;
        }
        return \yii\helpers\ArrayHelper::map($coures, 'id', 'title');
    }
}
