<?php

namespace app\modules\admin\models;

use Yii;

/**
 * This is the model class for table "trainings_date".
 *
 * @property integer $id
 * @property integer $training_id
 * @property integer $date_from
 * @property integer $date_to
 * @property integer $is_full_time
 * @property string $description
 * @property string $description_ru
 * @property string $description_en
 */
class TrainingsDate extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'trainings_date';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['training_id', 'date_from', 'date_to'], 'required'],
            [['training_id', 'is_full_time'], 'integer'],
            [['date_from', 'date_to'], 'safe'],
            [['description', 'description_ru', 'description_en'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'training_id' => 'Тренинг',
            'date_from' => 'Дата от',
            'date_to' => 'Дата по',
            'is_full_time' => 'Полное время',
            'description' => 'Описание',
            'description_ru' => 'Описание Ru',
            'description_en' => 'Описание En',
        ];
    }

    public function getTrainings(){
        return $this->hasOne(Trainings::className(), ['id'=>'training_id']);
    }

    public function beforeSave($insert)
    {
        $this->date_from = strtotime($this->date_from);
        $this->date_to = strtotime($this->date_to);
        return parent::beforeSave($insert);
    }

    public function afterFind()
    {
        $this->date_from = date("d-m-Y",$this->date_from);
        $this->date_to = date("d-m-Y",$this->date_to);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
