<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 19.10.2016
 * Time: 16:55
 */

namespace app\models;


use Yii;

class Imgmodel extends \yii\db\ActiveRecord
{
    public $image;
    public $imageAlt;
    public $imageTitle;

    protected $rule = [['image'], 'file', 'extensions' => 'png, jpg'];
    protected $rule2 = [['imageAlt','imageTitle'], 'string'];
    

    public function afterFind()
    {
        $arr = json_decode($this->img);
        $this->img = $arr->img;
        $this->imageAlt = $arr->alt;
        $this->imageTitle = $arr->title;

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

}