<?php
namespace app\models;

use yii\db\ActiveRecord;
use Yii;

class Partners extends ActiveRecord{
    public $image;
    public $imageAlt;
    public $imageTitle;
    public function afterFind()
    {
        $arr = json_decode($this->img);
        $this->image = $arr->img;
        $this->imageAlt = $arr->alt;
        $this->imageTitle = $arr->title;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}